version: "3"

volumes:
  signal-cli-config:

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - USE_NATIVE=0
    volumes:
      - "signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host

  pms:
    image: pms:latest
    environment:
      - APP_PORT=${APP_PORT}
      - SIGNAL_URL="http://signal-cli-rest-api:8080"
      - SIGNAL_SENDER=${SIGNAL_SENDER}
      - SIGNAL_RECIPIENT=${SIGNAL_RECIPIENT}
    ports:
      - "8001:${APP_PORT}"
